"""
Dashboard API models.

Defines the response model for:

    GET /api/v1/dashboard

Project: SHACK-SERVER
"""

from enum import Enum

from pydantic import BaseModel, Field


class Priority(str, Enum):
    """Priority levels used by recommendations."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class SummaryModel(BaseModel):
    """General dashboard summary."""

    uptime: str = Field(..., examples=["2d 14h 23m"])
    processed_spots: int = Field(..., ge=0)
    fusion_sources: int = Field(..., ge=0)
    latency_ms: int = Field(..., ge=0)
    cpu_percent: float = Field(..., ge=0, le=100)
    memory_percent: float = Field(..., ge=0, le=100)


class StationModel(BaseModel):
    """Current station status."""

    radio: str
    cat: bool
    cluster: bool
    internet: bool
    audio: bool
    ptt: bool


class PropagationModel(BaseModel):
    """Current propagation information."""

    solar_flux: int = Field(..., ge=0)
    a_index: int = Field(..., ge=0)
    k_index: int = Field(..., ge=0)


class ClusterModel(BaseModel):
    """Connected DX cluster."""

    name: str
    connected: bool
    latency_ms: int = Field(..., ge=0)


class RecommendationModel(BaseModel):
    """Recommendation generated by the Fusion Engine."""

    title: str
    message: str
    priority: Priority


class PriorityDxModel(BaseModel):
    """Priority DX station."""

    callsign: str
    band: str
    mode: str
    score: int = Field(..., ge=0)


class SpotSummaryModel(BaseModel):
    """Live spot displayed in the dashboard."""

    callsign: str
    frequency: float = Field(..., gt=0)
    mode: str
    source: str
    age_seconds: int = Field(..., ge=0)
    snr: float | None = None
    confidence: int = Field(..., ge=0, le=100)


class DashboardResponse(BaseModel):
    """Complete dashboard response."""

    summary: SummaryModel
    station: StationModel
    propagation: PropagationModel
    clusters: list[ClusterModel]
    recommendations: list[RecommendationModel]
    priority_dx: list[PriorityDxModel]
    live_spots: list[SpotSummaryModel]
